image: python:3.11

stages:
  - build_and_run

build_and_run:
  stage: build_and_run
  script:
    - pip install poetry
    - poetry --version
    - poetry install
    - poetry run python src/main.py
